# Generated by Django 4.2.9 on 2026-10-02 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=50, unique=True, verbose_name='案件编号')),
                ('title', models.CharField(max_length=200, verbose_name='案件名称')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应方')),
                ('description', models.TextField(blank=True, verbose_name='缺陷描述')),
                ('status', models.CharField(choices=[('open', '执行中'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='案件状态')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_recall_cases', to=settings.AUTH_USER_MODEL, verbose_name='关闭人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recall_cases', to=settings.AUTH_USER_MODEL, verbose_name='立案人')),
            ],
            options={
                'verbose_name': '召回案件',
                'verbose_name_plural': '召回案件',
                'db_table': 'wh_recall_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecallSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(default='create', max_length=30, verbose_name='触发动作')),
                ('batch_basis', models.JSONField(default=list, verbose_name='依据批次')),
                ('items', models.JSONField(default=list, verbose_name='影响清单快照')),
                ('summary', models.JSONField(default=dict, verbose_name='复算汇总')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='快照时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='warehouse.recallcase', verbose_name='所属案件')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '召回复算快照',
                'verbose_name_plural': '召回复算快照',
                'db_table': 'wh_recall_snapshot',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecallRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', '新增'), ('removed', '移除'), ('updated', '数量变更')], max_length=20, verbose_name='变更类型')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='批次号')),
                ('location_status', models.CharField(blank=True, max_length=20, verbose_name='库位状态')),
                ('qty_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='变更前数量')),
                ('qty_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='变更后数量')),
                ('reason', models.TextField(verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='warehouse.recallcase', verbose_name='所属案件')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_revisions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_revisions', to='warehouse.goods', verbose_name='货物')),
            ],
            options={
                'verbose_name': '召回清单变更',
                'verbose_name_plural': '召回清单变更',
                'db_table': 'wh_recall_revision',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecallItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, verbose_name='批次号')),
                ('location_status', models.CharField(choices=[('in_stock', '在库'), ('out', '已离库')], max_length=20, verbose_name='库位状态')),
                ('affected_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='受影响数量')),
                ('frozen_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='冻结数量')),
                ('receiver', models.CharField(blank=True, max_length=100, verbose_name='责任领用人')),
                ('receiver_dept', models.CharField(blank=True, max_length=100, verbose_name='领用部门')),
                ('last_known_status', models.CharField(blank=True, max_length=200, verbose_name='最后已知状态')),
                ('trace_detail', models.TextField(blank=True, verbose_name='谱系追溯说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否仍在影响清单')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='首次纳入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.recallcase', verbose_name='所属案件')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_items', to='warehouse.goods', verbose_name='受影响货物')),
                ('stock_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_items', to='warehouse.stockout', verbose_name='对应出库单')),
            ],
            options={
                'verbose_name': '召回影响条目',
                'verbose_name_plural': '召回影响条目',
                'db_table': 'wh_recall_item',
                'ordering': ['-is_active', 'case', 'id'],
                'unique_together': {('case', 'goods', 'batch_no', 'stock_out')},
            },
        ),
        migrations.CreateModel(
            name='RecallFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, verbose_name='批次号')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='冻结数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to='warehouse.recallcase', verbose_name='所属案件')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_freezes', to='warehouse.goods', verbose_name='冻结货物')),
            ],
            options={
                'verbose_name': '召回冻结',
                'verbose_name_plural': '召回冻结',
                'db_table': 'wh_recall_freeze',
                'ordering': ['case', 'id'],
                'unique_together': {('case', 'goods', 'batch_no')},
            },
        ),
        migrations.CreateModel(
            name='RecallBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, verbose_name='缺陷批次号')),
                ('source', models.CharField(choices=[('supplier_notice', '供应方通报'), ('internal_check', '内部排查'), ('regulatory_order', '监管指令'), ('other', '其他')], default='supplier_notice', max_length=30, verbose_name='依据来源')),
                ('notice_no', models.CharField(blank=True, max_length=100, verbose_name='通报文号')),
                ('evidence', models.TextField(blank=True, verbose_name='依据说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='warehouse.recallcase', verbose_name='所属案件')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recall_bases', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '召回依据',
                'verbose_name_plural': '召回依据',
                'db_table': 'wh_recall_basis',
                'ordering': ['id'],
                'unique_together': {('case', 'batch_no')},
            },
        ),
    ]
