# Generated by Django 4.2.9 on 2026-10-03 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(db_index=True, max_length=50, verbose_name='批次号')),
                ('relation', models.CharField(choices=[('root', '入库'), ('split', '拆分'), ('transfer', '转移'), ('collect', '领用')], default='root', max_length=20, verbose_name='与来源批次关系')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应方')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='批次数量')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='所在位置')),
                ('location_status', models.CharField(choices=[('in_stock', '在库'), ('out', '已离库')], default='in_stock', max_length=20, verbose_name='库位状态')),
                ('is_current', models.BooleanField(default=True, verbose_name='是否现存')),
                ('holder_name', models.CharField(blank=True, max_length=100, verbose_name='离库责任人')),
                ('holder_dept', models.CharField(blank=True, max_length=100, verbose_name='责任部门')),
                ('holder_contact', models.CharField(blank=True, max_length=50, verbose_name='责任人联系方式')),
                ('last_known_status', models.CharField(blank=True, max_length=200, verbose_name='最后已知状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='warehouse.goods', verbose_name='货物')),
                ('out_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='warehouse.stockout', verbose_name='出库记录')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='warehouse.batch', verbose_name='来源批次')),
            ],
            options={
                'verbose_name': '批次',
                'verbose_name_plural': '批次',
                'db_table': 'wh_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecallCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='案件名称')),
                ('case_no', models.CharField(max_length=50, unique=True, verbose_name='案件编号')),
                ('notified_batch_no', models.CharField(db_index=True, max_length=50, verbose_name='通报批次号')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='通报供应方')),
                ('basis', models.TextField(blank=True, verbose_name='召回依据')),
                ('defect_desc', models.TextField(blank=True, verbose_name='缺陷描述')),
                ('status', models.CharField(choices=[('open', '处置中'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='案件状态')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('close_remark', models.TextField(blank=True, verbose_name='关闭说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_recall_cases', to=settings.AUTH_USER_MODEL, verbose_name='关闭人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recall_cases', to=settings.AUTH_USER_MODEL, verbose_name='立案人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_cases', to='warehouse.goods', verbose_name='涉事物资')),
            ],
            options={
                'verbose_name': '召回案件',
                'verbose_name_plural': '召回案件',
                'db_table': 'wh_recall_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('split', '拆分'), ('transfer', '转移'), ('collect', '领用')], max_length=20, verbose_name='流转类型')),
                ('from_location', models.CharField(blank=True, max_length=100, verbose_name='原位置')),
                ('to_location', models.CharField(blank=True, max_length=100, verbose_name='目标位置')),
                ('holder_name', models.CharField(blank=True, max_length=100, verbose_name='领用人')),
                ('holder_dept', models.CharField(blank=True, max_length=100, verbose_name='领用部门')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='流转数量')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='流转时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.batch', verbose_name='流转批次')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_movements', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '批次流转事件',
                'verbose_name_plural': '批次流转事件',
                'db_table': 'wh_batch_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecallVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('snapshot', models.JSONField(default=list, verbose_name='影响清单快照')),
                ('added', models.JSONField(default=list, verbose_name='本次新增')),
                ('removed', models.JSONField(default=list, verbose_name='本次移除')),
                ('changed', models.JSONField(default=list, verbose_name='本次变更')),
                ('change_reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('frozen_count', models.PositiveIntegerField(default=0, verbose_name='在库冻结数')),
                ('out_count', models.PositiveIntegerField(default=0, verbose_name='已离库数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='复算时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='warehouse.recallcase', verbose_name='召回案件')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_versions', to=settings.AUTH_USER_MODEL, verbose_name='复算人')),
            ],
            options={
                'verbose_name': '召回清单版本',
                'verbose_name_plural': '召回清单版本',
                'db_table': 'wh_recall_version',
                'ordering': ['case', '-version_no'],
                'unique_together': {('case', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='RecallItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否仍在影响范围')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='是否已冻结')),
                ('impact_status', models.CharField(choices=[('in_stock', '在库已冻结'), ('out', '已离库')], default='in_stock', max_length=20, verbose_name='影响状态')),
                ('lineage_path', models.JSONField(default=list, verbose_name='谱系路径')),
                ('included_reason', models.CharField(blank=True, max_length=200, verbose_name='纳入依据')),
                ('holder_name', models.CharField(blank=True, max_length=100, verbose_name='离库责任人')),
                ('holder_dept', models.CharField(blank=True, max_length=100, verbose_name='责任部门')),
                ('holder_contact', models.CharField(blank=True, max_length=50, verbose_name='责任人联系方式')),
                ('last_known_status', models.CharField(blank=True, max_length=200, verbose_name='最后已知状态')),
                ('first_included_at', models.DateTimeField(auto_now_add=True, verbose_name='首次纳入时间')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='移出时间')),
                ('remove_reason', models.CharField(blank=True, max_length=200, verbose_name='移出原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_items', to='warehouse.batch', verbose_name='受影响批次')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.recallcase', verbose_name='召回案件')),
            ],
            options={
                'verbose_name': '召回影响项',
                'verbose_name_plural': '召回影响项',
                'db_table': 'wh_recall_item',
                'ordering': ['-created_at'],
                'unique_together': {('case', 'batch')},
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_no'], name='wh_batch_batch_n_7d5b82_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['location_status'], name='wh_batch_locatio_b8da90_idx'),
        ),
    ]
